# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: C++ MSBuild and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Configuration and platform settings
  BUILD_CONFIGURATION: Debug
  BUILD_PLATFORM: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Main Project
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} RealmOfFeasts.vcxproj

  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Test Project
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} tests/RealmOfFeastTest/RealmOfFeastTest.vcxproj

    - name: Run Tests from DLL
      run: |
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "tests\RealmOfFeastTest\x64\${{env.BUILD_CONFIGURATION}}\RealmOfFeastTest.dll"

  codecov_test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Make package json
        run: npm init -y

      - name: Install dependencies
        run: npm install --save-dev jest

      # - name: Run tests
      #   run: npx jest --coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test_CODACY:
    name: Run tests and collect coverage codacy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Make package json
        run: npm init -y

      - name: Install dependencies
        run: npm install --save-dev jest

      - name: Run tests
        run: npx jest --coverage

      - name: Upload results to Codacy
        run: |
          export CODACY_API_TOKEN=${{ secrets.CODACY_API_TOKEN }}
          export CODACY_ORGANIZATION_PROVIDER=${{ secrets.CODACY_ORGANIZATION_PROVIDER }}
          export CODACY_USERNAME=${{ secrets.CODACY_USERNAME }}
          export CODACY_PROJECT_NAME=${{ secrets.CODACY_PROJECT_NAME }}
          # Assuming you have the Codacy coverage uploader installed or available in your pipeline
          # You would run the coverage upload command here, for example:
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

